import type { Metadata } from "next";
import { Josefin_Sans, Lato } from 'next/font/google';
import "./globals.css";
import Header from '@/components/header'
import TopHeader from '@/components/topHeader'
import Footer from '@/components/footer'
import '@fontsource/josefin-sans/400.css';
import '@fontsource/josefin-sans/700.css';
import '@fontsource/lato/400.css';
import '@fontsource/lato/700.css';

const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  weight: ['400', '700'], // Add the weights you need
  variable: '--font-josefin-sans', // Define a custom CSS variable
});

const lato = Lato({
  subsets: ['latin'],
  weight: ['300', '400', '700'], // Add the weights you need
  variable: '--font-lato', // Define a custom CSS variable
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefinSans.variable} ${lato.variable}`}
      >
           <TopHeader/>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
